update

diff --git a/external-builder/bin/detect b/external-builder/bin/detect
--- a/external-builder/bin/detect
+++ b/external-builder/bin/detect
@@ -1,21 +1,25 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright IBM Corp. All Rights Reserved.
+# The bin/detect script is responsible for determining whether or not a buildpack 
+# should be used to build a chaincode package and launch it. 
 # 
-# SPDX-License-Identifier: Apache-2.0
+# The peer invokes detect with two arguments:
+# bin/detect CHAINCODE_SOURCE_DIR CHAINCODE_METADATA_DIR
+#
+# When detect is invoked, CHAINCODE_SOURCE_DIR contains the chaincode source and 
+# CHAINCODE_METADATA_DIR contains the metadata.json file from the chaincode package installed to the peer. 
+# The CHAINCODE_SOURCE_DIR and CHAINCODE_METADATA_DIR should be treated as read only inputs. 
+# If the buildpack should be applied to the chaincode source package, detect must return an exit code of 0; 
+# any other exit code will indicate that the buildpack should not be applied.
+
+CHAINCODE_METADATA_DIR="$2"
 
 set -euo pipefail
 
-if [ "$#" -ne 2 ]; then
-    >&2 echo "Expected 2 directories got $#"
-    exit 2
+# use jq to extract the chaincode type from metadata.json and exit with
+# success if the chaincode type is golang
+if [ "$(cat "$CHAINCODE_METADATA_DIR/metadata.json" | sed -e 's/[{}]/''/g' | awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'type'\042/){print $(i+1)}}}' | tr -d '"')" = "external" ]; then
+    exit 0
 fi
 
->&2 jq . "$2/metadata.json"
-
-if [ "$(jq -r .type "$2/metadata.json" | tr '[:upper:]' '[:lower:]')" != "golang" ]; then
-    >&2 echo "only golang chaincode supported"
-    exit 1
-fi
-
-
+exit 1
